Add support for MS Sharepoint using the MS Graph client
nearform/fastify-file-manager pull request #1
Opened 2021-04-16 13:15 UTC by Paul-Isache

2021-04-16 13:28 UTC, mcollina commented
Add a github action to run the tests.

2021-04-16 13:41 UTC, mcollina commented on example/example.js
> +  const response = await fastify.fileManager.getUsers().catch(err => console.log(err))
I'll drop the catch

2021-04-16 13:41 UTC, mcollina commented on example/example.js
> +  const response = await fastify.fileManager.getDrive().catch(err => console.log(err))
I'll drop the catch

2021-04-16 13:41 UTC, mcollina commented on example/example.js
> +  console.log('Server listenting on localhost:', fastify.server.address().port)
Fastify does this on its own.

2021-04-16 13:41 UTC, mcollina commented on src/sharepoint.js
> +require('isomorphic-fetch')
please do not use or require this as it pollutes the globals (if possible).

2021-04-16 13:41 UTC, mcollina commented on src/sharepoint.js
> +  init()
I would remove init, it's not needed

2021-04-16 13:41 UTC, mcollina commented on src/sharepoint.js
> +    const { accessToken } = await getAccessToken().catch(err => console.log(err))
```suggestion
    const { accessToken } = await getAccessToken()
```

2021-04-16 13:41 UTC, mcollina commented on src/sharepoint.js
> +  const getAccessToken = (scopes = tokenRequest) => {
```suggestion
  const getAccessToken = () => {
```

2021-04-16 13:56 UTC, Paul-Isache commented on example/example.js
> +  console.log('Server listenting on localhost:', fastify.server.address().port)
thanks for the input @mcollina .

2021-04-16 14:07 UTC, mcollina commented on src/sharepoint.js
> +    })
I think this allows a route to alter a global setting with user-specific credentials. I do not think it is correct.

2021-04-16 18:23 UTC, Paul-Isache commented on src/sharepoint.js
> +require('isomorphic-fetch')
the graph client requires fetch inside .. is either we use the MS package or we try and redo the calls calling directly the graph API

2021-04-17 03:41 UTC, Paul-Isache commented on src/sharepoint.js
> +    })
The credentials are app based not user based.

2021-04-17 08:09 UTC, mcollina commented on src/sharepoint.js
> +    })
Then this code is not correct, you should not be overriding the client.

2021-04-17 08:27 UTC, simoneb commented on src/sharepoint.js
> +    })
If it's of any use, in brokeneck we're doing something similar to use the ms graph client library. The difference is we're not using the msal library for authentication but doing it manually instead. In general I found ms libraries extremely confusing to use, often because there are many versions and flavors of packages out there and it's often not obvious what you should use and what's deprecated. Also, because they often support many features while you only need one.

In this PR there is an attempt at using ms graph client and doing manual authentication instead of using msal. Not suggesting it's better, just an alternative way which works just fine. 

https://github.com/nearform/brokeneck/pull/30/files#diff-b23f45aa9ac21d43093d45d909dad766e05bf234cbd2c1066ceec6ce72243679

2021-04-17 11:58 UTC, mcollina requested changes

2021-04-18 07:40 UTC, Paul-Isache commented on src/sharepoint.js
> +    })
Thank @simoneb!

The opened PR is similar to the one here, with the difference that in there the authentication is done in your method, but still adding the authProvider as a middleware, which is also described in their documentation.
An alternative would be to use the MSAL lib for authentication and instead of the graph-client to use the API with direct calls and adding on each request the authorization header with the generated token. This way, we would avoid overriding the client as we are not using it.

2021-04-19 10:56 UTC, Paul-Isache commented on src/sharepoint.js
> +  tokenRequest.scopes = options.config.scopes
refactored

2021-04-19 10:57 UTC, Paul-Isache commented
replaced graph client with a API direct call in order to avoid overriding

2021-04-19 21:59 UTC, mcollina commented on test.js
> +    sharepoint({ config: {} })
is an error expected here? If so, we should have an assertion that fails if there is not one.

2021-04-19 21:59 UTC, mcollina commented on test.js
> +  t.end()
this is not needed

2021-04-19 21:59 UTC, mcollina commented on test.js
> +test('set the sharepoint decorator integrated with fastify', async (t) => {
I think assertions are needed here

2021-04-20 08:08 UTC, Paul-Isache commented on test.js
> +test('set the sharepoint decorator integrated with fastify', async (t) => {
I will add assertions

2021-04-20 10:36 UTC, mcollina reviewed
good work!

2021-04-20 10:36 UTC, mcollina commented on test.js
> +// const assert = require('assert')
```suggestion
```

2021-04-20 13:30 UTC, simoneb reviewed
don't forget to add a CI which runs your checks automatically :)

2021-04-20 18:26 UTC, Paul-Isache commented
will add ci to run the checks.. thanks @simoneb

2021-04-20 21:21 UTC, mcollina approved these changes
lgtm

2021-04-21 14:45 UTC, litzenberger approved these changes
looks good!!

2021-04-21 17:42 UTC, merged